package swagger

import (
	_ "github.com/Tap-Team/timerapi/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title			Timer API Swagger
// @version		1.0
// @termsOfService	http://swagger.io/terms/
// @license.name	Apache 2.0
// @license.url	http://www.apache.org/licenses/LICENSE-2.0.html
//
// @host			localhost:12700
// @BasePath		/
func New(e *echo.Echo) {
	e.GET("/swagger/*", echoSwagger.WrapHandler)
}
