package timernotificationstream

import (
	"github.com/Tap-Team/timerapi/internal/model/notification"
	"github.com/google/uuid"
)

type UserStream struct {
	// pointer to handler
	handler *StreamHandler
	// unique stream id (autogenerated)
	id uuid.UUID
	// user id to track user timers
	userId int64
	// chan for stream notification
	ch chan notification.Notification
}

func (sh *StreamHandler) NewUserStream(userId int64) interface {
	Stream() <-chan notification.Notification
	Close()
} {
	id := uuid.New()
	stream := &UserStream{handler: sh, id: id, userId: userId, ch: make(chan notification.Notification, 10)}
	sh.mu.Lock()
	if _, ok := sh.subscribers[userId]; !ok {
		sh.subscribers[userId] = make(map[uuid.UUID]*UserStream)
	}
	sh.subscribers[userId][id] = stream
	sh.mu.Unlock()
	return stream
}

func (s *UserStream) Close() {
	s.handler.mu.Lock()
	delete(s.handler.subscribers[s.userId], s.id)
	if len(s.handler.subscribers[s.userId]) == 0 {
		delete(s.handler.subscribers, s.userId)
	}
	close(s.ch)
	s.handler.mu.Unlock()
}

func (s *UserStream) Stream() <-chan notification.Notification {
	return s.ch
}
